spring.application.name=Fitness Tracker

server.port=8586

spring.datasource.url = jdbc:mysql://localhost:3307/fitness_db?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=852963

#JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# SQL Debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

# JWT Configuration
jwt.secret=70c7adc3d35ff0783491f6074d99b0a2ca307de26bcc64c85163e04f2d8bbddc

# 86400000 = 24 hours. (8640000 = 2.4 hours)
jwt.expiration=86400000